---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device
  namespace: dev
  labels:
    app: device
spec:
  selector:
    matchLabels:
      app: device
  template:
    metadata:
      labels:
        app: device
    spec:
      containers:
        - name: device
          image: registry.ngaxavilabs.com/devops/device
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: device
                optional: false
          env:
            - name: KAFKA_PREFIX
              value: dev
            - name: KAFKA_HOST
              value: kafka.kafka
            - name: KAFKA_PORT
              value: '9094'
            - name: CREDENTIALS
              value: WGF2aWVyOnplZHFxdWxyZnFxYwo=
      imagePullSecrets:
        - name: registry-devops

---
apiVersion: v1
kind: Service
metadata:
  name: device
  namespace: dev
  labels:
    app: device
spec:
  selector:
    app: device
  ports:
    - port: 3000
      name: device-port
      targetPort: 3000
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: device
  namespace: dev
  labels:
    app: device
stringData:
  MONGO_USER: device-service
  MONGO_PASSWORD: WzyF86Ec5j64Kcsag1UH
  MONGO_HOST: database
  PORT: '3000'
type: Opaque

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: device
  namespace: dev
  labels:
    app: device
spec:
  tls:
    - hosts:
        - testing.devopsapp.ngaxavilabs.com
      secretName: testing-devopsapp-ngaxavilabs-com-tls
  rules:
    - host: testing.devopsapp.ngaxavilabs.com
      http:
        paths:
          - backend:
              serviceName: device
              servicePort: 3000
            path: /api/devices
